#!/bin/bash
set -e

echo "[*] Forzando /bin/bash como shell final del sistema"

# Cambiar shell por defecto global
sed -i 's|^DSHELL=.*|DSHELL=/bin/bash|' /etc/adduser.conf
sed -i 's|^SHELL=.*|SHELL=/bin/bash|' /etc/default/useradd

# Forzar root
chsh -s /bin/bash root || true

# Forzar usuario creado durante instalación
for user in $(awk -F: '$3>=1000 && $1!="nobody"{print $1}' /etc/passwd); do
    chsh -s /bin/bash "$user" || true
done

echo "[*] Bash forzado en todos los usuarios"
